# Generated by Django 3.2.6 on 2021-08-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_remove_doctor_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.TextField(verbose_name='Symptoms')),
                ('specialit', models.ManyToManyField(to='doctor.Specialist')),
            ],
        ),
    ]
