# Generated by Django 3.2.6 on 2021-08-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Hospital Name')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Hospital Address')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Number')),
                ('image', models.ImageField(blank=True, default='hospital.png', null=True, upload_to='hospital/', verbose_name='Hospital Image')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, max_length=10, null=True, verbose_name='Consulting Hour Start')),
                ('end', models.CharField(blank=True, max_length=10, null=True, verbose_name='Consulting Hour End')),
                ('fees', models.CharField(blank=True, max_length=10, null=True, verbose_name='Consulting Fees')),
                ('days', models.CharField(blank=True, max_length=255, null=True, verbose_name='Consulting Days')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
