# Generated by Django 3.2.6 on 2021-08-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_work'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='doctor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
            preserve_default=False,
        ),
    ]
