# Generated by Django 3.2.6 on 2021-08-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Specialist Name')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Doctor ID')),
                ('name', models.CharField(max_length=100, verbose_name='Doctor Name')),
                ('qualification', models.TextField(blank=True, max_length=450, null=True, verbose_name='Qualification')),
                ('designation', models.TextField(blank=True, max_length=450, null=True, verbose_name='Designation')),
                ('specialist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.specialist', verbose_name='Specialist Name')),
            ],
        ),
    ]
