# Generated by Django 3.2.6 on 2021-08-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='doctors.png', null=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='work',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospital.works'),
            preserve_default=False,
        ),
    ]
